/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-07-17 10:23:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reservation_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 탑승 인원 - 증가, 감소 로직  -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tfunction modifyProductQuantity(id, quantity){\r\n");
      out.write("\t    \r\n");
      out.write("\t    if(isNaN($(\"#\"+id).val())){\r\n");
      out.write("\t         alert( '숫자만 입력가능 합니다.' );\r\n");
      out.write("\t         $(\"#\"+id).focus();\r\n");
      out.write("\t         $(\"#\"+id).val(0);\r\n");
      out.write("\t         return;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    var q = parseInt($(\"#\"+id).val())+parseInt(quantity);\r\n");
      out.write("\t    if(q < 0) {\r\n");
      out.write("\t    \talert('더 이상 줄일 수 없습니다.');\r\n");
      out.write("\t    \tq = 0;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    $(\"#\"+id).val(q);\r\n");
      out.write("\t    \r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 주요공항 리스트 레이어 display 변경 로직  -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction openAirportList(param) {\r\n");
      out.write("\t\tif(param.style.display == \"none\") {\r\n");
      out.write("\t\t\tparam.style.display = \"block\"\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tparam.style.display = \"none\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 공항 선택시 input태그 공항 변경 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction setDepAirport(param) {\r\n");
      out.write("\t\tvar select = $(param).text();\r\n");
      out.write("\t\t$(\"#depAirport\").val(select);\r\n");
      out.write("\t\t$(\"#dep_airport_list\").css(\"display\", \"none\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction setArrAirport(param) {\r\n");
      out.write("\t\tvar select = $(param).text();\r\n");
      out.write("\t\t$(\"#arrAirport\").val(select);\r\n");
      out.write("\t\t$(\"#arr_airport_list\").css(\"display\", \"none\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 편도, 왕복 Ajax 로직 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#onewayTrip\").click(function() {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'oneway_trip.jsp',\r\n");
      out.write("\t\t\t\tdataType : 'html',\r\n");
      out.write("\t\t\t\ttype : 'get',\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tvar refine = $(\".depArr_date\").html(result).find('table')\r\n");
      out.write("\t\t\t\t\t$(\".depArr_date\").html(refine)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#tripType\").val(\"편도\");\r\n");
      out.write("\t\t\t$(\"#onewayTrip\").css(\"background-color\", \"crimson\")\r\n");
      out.write("\t\t\t$(\"#onewayTrip\").css(\"color\", \"white\")\r\n");
      out.write("\t\t\t$(\"#roundTrip\").css(\"background-color\", \"white\")\r\n");
      out.write("\t\t\t$(\"#roundTrip\").css(\"color\", \"black\")\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$(\"#roundTrip\").click(function() {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'round_trip.jsp',\r\n");
      out.write("\t\t\t\tdataType : 'html',\r\n");
      out.write("\t\t\t\ttype : 'get',\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tvar refine = $(\".depArr_date\").html(result).find('table')\r\n");
      out.write("\t\t\t\t\t$(\".depArr_date\").html(refine)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#tripType\").val(\"왕복\");\r\n");
      out.write("\t\t\t$(\"#roundTrip\").css(\"background-color\", \"crimson\")\r\n");
      out.write("\t\t\t$(\"#roundTrip\").css(\"color\", \"white\")\r\n");
      out.write("\t\t\t$(\"#onewayTrip\").css(\"background-color\", \"white\")\r\n");
      out.write("\t\t\t$(\"#onewayTrip\").css(\"color\", \"black\")\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tshowSlides();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 공항 검색 자동완성 Ajax 로직 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    $(function() {\r\n");
      out.write("    \t$(\"#depAirport\").autocomplete({\r\n");
      out.write("    \tsource : function(request, response) {\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("    \t\t\turl : 'autocomplete_json.jsp',\r\n");
      out.write("    \t\t\tdataType : 'json',\r\n");
      out.write("    \t\t\ttype : 'get',\r\n");
      out.write("    \t\t\tsuccess : function(result) { //성공시\r\n");
      out.write("    \t\t\t\tresponse(\r\n");
      out.write("    \t\t\t\t\t$.map(result, function(item) {\r\n");
      out.write("    \t\t\t\t\t\tif(item.location.indexOf($(\"#depAirport\").val()) >= 0) {\r\n");
      out.write("    \t\t\t\t\t\t\treturn {\r\n");
      out.write("        \t\t\t\t\t\t\tlabel: item.location + \" \" +item.code,\r\n");
      out.write("        \t\t\t\t\t\t\tvalue: item.location + \" \" + item.code\r\n");
      out.write("        \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t})\r\n");
      out.write("    \t\t\t\t); //response-end\r\n");
      out.write("    \t\t\t},\r\n");
      out.write("    \t\t\terror : function(e) {\r\n");
      out.write("    \t\t\t\talert(\"통신에 실패했습니다.\");\r\n");
      out.write("    \t\t\t\tconsole.dir(e);\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t}, //source-end\r\n");
      out.write("    \tminLength : 1,\r\n");
      out.write("    \tautoFocus : false,\r\n");
      out.write("    \tselect : function(evt, ui) {\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t},\r\n");
      out.write("    \tfocus : function(evt, ui) {\r\n");
      out.write("    \t\treturn false;\r\n");
      out.write("    \t},\r\n");
      out.write("    \tclose : function(evt) {\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t$(\"#arrAirport\").autocomplete({\r\n");
      out.write("        \tsource : function(request, response) {\r\n");
      out.write("        \t\t$.ajax({\r\n");
      out.write("        \t\t\turl : 'autocomplete_json.jsp',\r\n");
      out.write("        \t\t\tdataType : 'json',\r\n");
      out.write("        \t\t\ttype : 'get',\r\n");
      out.write("        \t\t\tsuccess : function(result) { //성공시\r\n");
      out.write("        \t\t\t\tconsole.log(result);\r\n");
      out.write("        \t\t\t\tresponse(\r\n");
      out.write("        \t\t\t\t\t$.map(result, function(item) {\r\n");
      out.write("        \t\t\t\t\t\tif (item.location.indexOf($(\"#arrAirport\").val()) >= 0) {\r\n");
      out.write("        \t\t\t\t\t\t\treturn {\r\n");
      out.write("            \t\t\t\t\t\t\tlabel: item.location + \" \" +item.code,\r\n");
      out.write("            \t\t\t\t\t\t\tvalue: item.location + \" \" + item.code\r\n");
      out.write("            \t\t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t\t\t}\r\n");
      out.write("        \t\t\t\t\t})\r\n");
      out.write("        \t\t\t\t); //response-end\r\n");
      out.write("        \t\t\t},\r\n");
      out.write("        \t\t\terror : function(e) {\r\n");
      out.write("        \t\t\t\talert(\"통신에 실패했습니다.\");\r\n");
      out.write("        \t\t\t\tconsole.dir(e);\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t});\r\n");
      out.write("        \t}, //source-end\r\n");
      out.write("        \tminLength : 1,\r\n");
      out.write("        \tautoFocus : false,\r\n");
      out.write("        \tselect : function(evt, ui) {\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t},\r\n");
      out.write("        \tfocus : function(evt, ui) {\r\n");
      out.write("        \t\treturn false;\r\n");
      out.write("        \t},\r\n");
      out.write("        \tclose : function(evt) {\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t}\r\n");
      out.write("        \t});\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/* Noto Sans KR 폰트 추가 */\r\n");
      out.write("@import url(http://fonts.googleapis.com/earlyaccess/notosanskr.css);\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\tfont-size: initial;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.container {\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.container_submit {\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body {\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tz-index: 90;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section {\r\n");
      out.write("\tmargin: 2%;\r\n");
      out.write("\tmargin-top: 13%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<title>여정 선택</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header.jsp", out, false);
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"sectionId\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<form action=\"reservation_result.rsv\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"trip_type\">\r\n");
      out.write("\t\t\t\t\t<h2>여정/날짜 선택</h2>\r\n");
      out.write("\t\t\t\t\t<table class=\"selectTripType\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"button\" id=\"onewayTrip\" value=\"편도\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 80px; height: 30px; background-color: crimson; color: white; font-weight: bold;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"button\" id=\"roundTrip\" value=\"왕복\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 80px; height: 30px; background-color: white; color: black; font-weight: bold;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"hidden\" id=\"tripType\" name=\"tripType\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"편도\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- tab_trip_type end -->\r\n");
      out.write("\t\t\t\t<div class=\"depArr_date\">\r\n");
      out.write("\t\t\t\t\t<table class=\"tab_selectDepArr\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: 0px; border-spacing: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dep\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"depAirport\">출발지</label> <br> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" id=\"depAirport\" name=\"depAirport\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonFocus=\"this.value=''; return true;\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 200px; height: 50px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn_airport_list1\" style=\"position: relative;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button name=\"btn_airport_list1\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript: openAirportList(document.getElementById('dep_airport_list'));\">주요도시\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t바로선택</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dep_airport_list\" id=\"dep_airport_list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"position: absolute; display: none; border: 1px solid black; background-color: white; padding: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong class=\"airport_list_title\">주요도시 바로선택</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h5>국내선</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul style=\"list-style: none; padding-left: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#none\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript: setDepAirport(this);\">서울/인천 ICN</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#none\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript: setDepAirport(this);\">서울/김포 GMP</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"arr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"arrAirport\">도착지</label> <br> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" id=\"arrAirport\" name=\"arrAirport\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonFocus=\"this.value=''; return true;\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 200px; height: 50px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn_airport_list2\" style=\"position: relative;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button name=\"btn_airport_list2\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript: openAirportList(document.getElementById('arr_airport_list'));\">주요도시\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t바로선택</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"arr_airport_list\" id=\"arr_airport_list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"position: absolute; display: none; border: 1px solid black; background-color: white; padding: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong class=\"airport_list_title\">주요도시 바로선택</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h5>국내선</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul style=\"list-style: none; padding-left: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#none\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript: setArrAirport(this);\">서울/김포 GMP</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"boardingDate\">탑승일</label> <br> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"date\" id=\"boardingDate\" name=\"bDate\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 200px; height: 50px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- tab_depArr_date end -->\r\n");
      out.write("\t\t\t\t<div class=\"passenger\">\r\n");
      out.write("\t\t\t\t\t<h2>탑승 인원 선택</h2>\r\n");
      out.write("\t\t\t\t\t<table class=\"selectPassenger\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: 0px; border-spacing: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pass_adult\" id=\"adult\" style=\"display: block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t성인&nbsp;<span id=\"adultAge\">(만 12세 이상)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn_number_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" name=\"btn_number_minus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript:modifyProductQuantity('adultCnt', -1);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"-\" style=\"width: 30px; height: 30px;\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" id=\"adultCnt\" name=\"adultCount\" title=\"성인 탑승 인원\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center; width: 120px; height: 25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" name=\"btn_number_plus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript:modifyProductQuantity('adultCnt', 1);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"+\" style=\"width: 30px; height: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pass_child\" id=\"child\" style=\"display: block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t소아&nbsp;<span id=\"childAge\">(만 2세 ~ 12세 미만)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn_number_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" name=\"btn_number_minus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript:modifyProductQuantity('childCnt', -1);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"-\" style=\"width: 30px; height: 30px;\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" id=\"childCnt\" name=\"childCount\" title=\"소아 탑승 인원\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center; width: 120px; height: 25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" name=\"btn_number_plus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript:modifyProductQuantity('childCnt', 1);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"+\" style=\"width: 30px; height: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pass_baby\" id=\"baby\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t유아&nbsp;<span id=\"babyAge\">(만 2세 미만)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"btn_number_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" name=\"btn_number_minus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript:modifyProductQuantity('babyCnt', -1);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"-\" style=\"width: 30px; height: 30px;\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" id=\"babyCnt\" name=\"babyCount\" title=\"유아 탑승 인원\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center; width: 120px; height: 25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" name=\"btn_number_plus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript:modifyProductQuantity('babyCnt', 1);\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"+\" style=\"width: 30px; height: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- tab_passenger end -->\r\n");
      out.write("\t\t\t\t<div class=\"container_submit\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"항공권 조회\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 100px; height: 40px;\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- container end -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<footer>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./footer.jsp", out, false);
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
