/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-07-17 11:29:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kaja_air.admin.DAO.AdminDAO;
import com.kaja_air.admin.VO.AdmimVO;

public final class AdminNotice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1593517452000L));
    _jspx_dependants.put("jar:file:/D:/Java_Web_PM_Class_JB/project/Kaja_Airline_final/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KajaAirline/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kaja_air.admin.VO.AdmimVO");
    _jspx_imports_classes.add("com.kaja_air.admin.DAO.AdminDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.adminNoticeTable{\r\n");
      out.write("\t\t/* width = \"650\" align=\"center\"; */\r\n");
      out.write("\t\twidth: 50%;\r\n");
      out.write("\t\tmargin-left: auto;\r\n");
      out.write("\t\tmargin-right: auto;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\twindow.onload=function(){\r\n");
      out.write("\t\tif(\"");
      out.print(session.getAttribute("id"));
      out.write("\"==\"admin\"){\r\n");
      out.write("\t\t\tdocument.getElementById(\"adminwrite\").style.display=\"block\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tshowSlides();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	request.setCharacterEncoding("EUC-KR");
AdminDAO tidao = new AdminDAO(); //객체 생성
ArrayList<AdmimVO> tiArray = tidao.getNoticeList();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section id=\"sectionId\" style=\"text-align: center;margin-left: auto;margin-right: auto;\">\r\n");
      out.write("\t<h1 style=\"text-align: center;font-size: 25pt;\">공지사항</h1>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"NoticeWrite.jsp\">\r\n");
      out.write("\t<table border=\"2\" class=\"adminNoticeTable\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"text-align: center;width: 10%;\">글번호</td>\r\n");
      out.write("\t\t\t<td style=\"text-align: center;width: 60%%;\">제목</td>\r\n");
      out.write("\t\t\t<td style=\"text-align: center;width: 30%;\">날짜</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");

						for(AdmimVO imsi : tiArray){
					
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr onclick=\"location.href='NoticeContent.do?nNo=");
      out.print(imsi.getnNo());
      out.write("&fileName1=");
      out.print(imsi.getnFname());
      out.write("&num=");
      out.print(imsi.getnNo() );
      out.write("'\" style=\"cursor:pointer;\">\t\r\n");
      out.write("\t\t\t<td>");
      out.print(imsi.getnNo());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(imsi.getnTitle() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(imsi.getnDate());
      out.write("</td>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <input type=\"hidden\" value=\"");
      out.print(imsi.getnFname() );
      out.write("\"name=\"fileName1\" />\r\n");
      out.write("    <input type=\"hidden\" value=\"");
      out.print(imsi.getnNo() );
      out.write("\" name=\"num\"/>\r\n");
      out.write("    \t\t");
}
      out.write("</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br><hr>\r\n");
      out.write("\t<div id=\"adminwrite\" style=\"display: none;text-align: center;\">\r\n");
      out.write("\t<input  style=\"font-size: 17pt;padding: 5px;\" type=\"submit\" value=\"글쓰기\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</section>\r\n");
      out.write("<footer>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
