/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-07-17 08:58:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.oreilly.servlet.MultipartRequest;
import com.kaja_air.admin.VO.AdmimVO;
import java.util.ArrayList;
import com.kaja_air.admin.DAO.AdminDAO;

public final class getAllSchedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1593517452000L));
    _jspx_dependants.put("jar:file:/D:/Java_Web_PM_Class_JB/project/Kaja_Airline_final/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KajaAirline/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kaja_air.admin.VO.AdmimVO");
    _jspx_imports_classes.add("com.oreilly.servlet.MultipartRequest");
    _jspx_imports_classes.add("com.kaja_air.admin.DAO.AdminDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>스케줄 전체보기</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("\tbackground-image: url(\"./imgs/bg.jpg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" \t#main{\r\n");
      out.write(" \t\tfloat:left;\r\n");
      out.write(" \t\twidth: 46%;\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write(" \t#main2{\r\n");
      out.write(" \tfloat:right;\r\n");
      out.write(" \twidth:46%;\r\n");
      out.write(" \t\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"./js/jquery-3.1.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.onload=function setSign() {\r\n");
      out.write("\t\t\tshowSlides();\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("EUC-KR");
AdminDAO tidao = new AdminDAO(); //객체 생성
ArrayList<AdmimVO> tiArray = tidao.getSchedule();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section id=\"sectionId\">\r\n");
      out.write("\r\n");
      out.write("<div style=\"width: 100%;\">\r\n");
      out.write("\r\n");
      out.write("\t<table id=\"main\" border=\"1\">\r\n");
      out.write("\t<tr><td colspan=\"8\"><h1>항공 스케줄</h1></td></tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>스케줄ID</td><td>출발 시각</td><td>도착 시각</td><td>출발지</td><td>도착지</td><td>성인가격</td><td>소인가격</td><td>유아가격</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t");

			for(AdmimVO imsi : tiArray){
		
      out.write("\r\n");
      out.write("\t<tr onclick=\"location.href='ScheduleSearchOne.do?pId=");
      out.print(imsi.getpId() );
      out.write("&pDeparture=");
      out.print(imsi.getpDTime() );
      out.write("&pArrive=");
      out.print(imsi.getpArrive() );
      out.write("'\"  style=\"cursor:pointer;\">\r\n");
      out.write("\t<td>");
      out.print(imsi.getpId() );
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(imsi.getpDTime() );
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(imsi.getpATime() );
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(imsi.getpDeparture() );
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(imsi.getpArrive() );
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(imsi.getpChildPrice() );
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(imsi.getpAdultPrice() );
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print(imsi.getpBabyPrice() );
      out.write("</td>\r\n");
      out.write("\t");
} 
      out.write("</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<fieldset id=\"main2\">\r\n");
      out.write("\t\t<div style=\"font-weight: bold;font-size: 20pt;\">스케줄 삽입</div>\r\n");
      out.write("\t     <legend>파일 업로드</legend>\r\n");
      out.write("\t     <form action=\"InsertFileText.jsp\">\r\n");
      out.write("\t     <table>\r\n");
      out.write("\t     <tr>\r\n");
      out.write("\t     \r\n");
      out.write("\r\n");
      out.write("\t     <td><input type=\"file\" value=\"파일 선택\" name=\"file\"/></td>\t\r\n");
      out.write("\t     <td><input type=\"submit\" value=\"파일입력\"/></td>\r\n");
      out.write("\t     </tr>\r\n");
      out.write("\t     </table>\r\n");
      out.write("\t      </form>\r\n");
      out.write("\r\n");
      out.write("</fieldset>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("<footer>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
