/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-07-17 08:25:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.Console;
import com.kaja_air.index.DAO.KajaDAO;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kaja_air.index.DAO.KajaDAO");
    _jspx_imports_classes.add("java.io.Console");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html, body {\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@import url(http://fonts.googleapis.com/earlyaccess/notosanskr.css);\r\n");
      out.write("\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tinput {\r\n");
      out.write("\t\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t\tfont-size: initial;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("\twidth : 100%;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\ttop : 0;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tbackground-color : white;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tz-index: 90;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section{\r\n");
      out.write("\tmin-height:450px;\r\n");
      out.write("\tmargin: 2%;\r\n");
      out.write("    margin-top: 13%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 20%;\r\n");
      out.write("\tz-index: 90;\r\n");
      out.write("}\r\n");
      out.write(".menuBar {\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\theight: 10%;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground-color: #93b3ef;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\talign-self: center;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-style: italic;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Slideshow container */\r\n");
      out.write(".slideshow-container {\r\n");
      out.write(" \twidth: 77%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    \r\n");
      out.write("    z-index: 50;  \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".imgSlides {display: none; position: relative; left: 0;}\r\n");
      out.write("img {vertical-align: middle;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 헤더 공지사항 관련 */\r\n");
      out.write(".notice-container {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tbackground-color: #a3d1e7;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\t/* cookie */\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".noticeSlides {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cook {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 40px;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-style: italic;\r\n");
      out.write("\ttop: 6%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cookDot {\r\n");
      out.write("\tright: 0.5%;\r\n");
      out.write("\ttop: 6%;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tbackground-color: #c4c3bb;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* header menu & drop */\r\n");
      out.write(".dropbtn {\r\n");
      out.write("\tbackground-color: #93b3ef;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 16px;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbackground-color: #f1f1f1;\r\n");
      out.write("\tmin-width: 160px;\r\n");
      out.write("\tbox-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);\r\n");
      out.write("\tz-index: 99;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tfont-size: 14pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("\tcolor: #6e6b58;\r\n");
      out.write("\tpadding: 12px 16px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tleft: inherit;\r\n");
      out.write("}\r\n");
      out.write("/* css 가상가상클래스 hover Element위에 마우스가 올라올때를 말함 */\r\n");
      out.write(".dropdown-content a:hover {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown {\r\n");
      out.write("\tfont-size: 15pt;\r\n");
      out.write("\tvertical-align: bottom;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".dropbtn:hover  .dropbtn{\r\n");
      out.write("\tbackground-color: #232326;\r\n");
      out.write("}\r\n");
      out.write(".dropbtn:hover  .dropdown-content {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write(".dropbtnAdmin:hover  .dropdown-content {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tmargin: auto auto;\r\n");
      out.write("\twidth: 33%;\r\n");
      out.write("\theight: 480px;\r\n");
      out.write("\tleft: 30%;\r\n");
      out.write("\ttop: 90%;\r\n");
      out.write("\tfont-size: 25pt;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: #dfe4e8;\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".loginInput {\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tpadding: 3px;\r\n");
      out.write("\tborder: 1px solid;\r\n");
      out.write("\tfont-size: 20pt;\r\n");
      out.write("\tmargin-top: 15px;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".loginButton {\r\n");
      out.write("\twidth: 23%;\r\n");
      out.write("\theight: 10%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 3px;\r\n");
      out.write("\tborder: 0.5pxs;\r\n");
      out.write("\tfont-size: 20pt;\r\n");
      out.write("\tmargin-bottom: 1%;\r\n");
      out.write("}\r\n");
      out.write("/* Caption text */\r\n");
      out.write(".text {\r\n");
      out.write("  /* color: #000000; */\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("  padding: 8px 12px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 80px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("/* Fading animation */\r\n");
      out.write(".fade {\r\n");
      out.write("  -webkit-animation-name: fade;\r\n");
      out.write("  -webkit-animation-duration: 1.8s;\r\n");
      out.write("  animation-name: fade;\r\n");
      out.write("  animation-duration: 1.8s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes fade {\r\n");
      out.write("  from {opacity: .1} \r\n");
      out.write("  to {opacity: 1}\r\n");
      out.write("} \r\n");
      out.write("@keyframes fade {\r\n");
      out.write("  from {opacity: .1} \r\n");
      out.write("  to {opacity: 1}\r\n");
      out.write("}\r\n");
      out.write("/* 유진씨 버튼 */\r\n");
      out.write(".button {\r\n");
      out.write("\tfont-size: 12pt;\r\n");
      out.write("\tpadding : 3px;\r\n");
      out.write("\twidth: 10%;\r\n");
      out.write("}\r\n");
      out.write(".buttonUpdate {\r\n");
      out.write("\tfont-size: 13pt;\r\n");
      out.write("\tpadding : 8px;\r\n");
      out.write("\twidth: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* On smaller screens, decrease text size */\r\n");
      out.write("@media only screen and (max-width: 300px) {\r\n");
      out.write("  .text {font-size: 11px}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");
request.setCharacterEncoding("EUC-KR"); 
	response.setCharacterEncoding("EUC-KR");
	KajaDAO da=new KajaDAO();
	String[] result=new String[3]; 
	result=da.getNoticeHeader();
	
	
      out.write("\r\n");
      out.write("\t<!-- 공지사항부분  쿠키 사용하여 하루창안보기등...셋팅해야됨. 체크박스도-->\r\n");
      out.write("\t<div class=\"notice-container\">\r\n");
      out.write("\t\t<table style=\"width: 100%\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width: 70%;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"noticeSlides fade\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(result[0] );
      out.write(" <a href=\"AdminNotice.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"font-size: 12px; text-decoration: none; color: white;\">>>자세히\r\n");
      out.write("\t\t\t\t\t\t\t보기</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"noticeSlides fade\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(result[1] );
      out.write(" <a href=\"AdminNotice.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"font-size: 12px; text-decoration: none; color: white;\">>>자세히\r\n");
      out.write("\t\t\t\t\t\t\t보기</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"noticeSlides fade\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(result[2] );
      out.write(" <a href=\"AdminNotice.jsp\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"font-size: 12px; text-decoration: none; color: white;\">>>자세히\r\n");
      out.write("\t\t\t\t\t\t\t보기</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td style=\"width: 30%;\"><span class=\"cook\"> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"checkbox\" name=\"cook\">오늘 하루 보지 않기\r\n");
      out.write("\t\t\t\t</span> <a href=\"javascript:void(0)\" onclick=\"setCookie()\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"cookDot\">X</span></a></td>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"login\">\r\n");
      out.write("\t\t<!-- login 창 부분 -->\r\n");
      out.write("\t\t<div style=\"text-align: right; width: 100%; height: 5%;\">\r\n");
      out.write("\t\t\t<a style=\"text-decoration: none; font-size: 15pt; color: black;\"\r\n");
      out.write("\t\t\t\thref=\"javascript:void(0)\" onclick=\"popupLogin2()\">x&nbsp;</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<table style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"font-size: 35pt;\">로그인\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" class=\"loginInput\" id=\"clientId\"\r\n");
      out.write("\t\t\t\t\tvalue=\"아이디 입력\" onfocus=\"this.select()\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" class=\"loginInput\" id=\"clientPw\"\r\n");
      out.write("\t\t\t\t\tvalue=\"비밀번호 입력\" onfocus=\"changePw(this.id)\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<!-- <div\r\n");
      out.write("\t\t\tstyle=\"left: 30%; position: relative; text-align: left; width: 40%; font-weight: lighter;\">\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"confirmPw\"><span\r\n");
      out.write("\t\t\t\tstyle=\"font-size: 10pt;\">비밀번호 확인하기</span> -->\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t<!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"button\" class=\"loginButton\" value=\"로 그 인\"\r\n");
      out.write("\t\t\tonclick=\"login()\"> <input type=\"button\" class=\"loginButton\"\r\n");
      out.write("\t\t\tvalue=\"회원가입\" onclick=\"location.replace('Signup.jsp')\">\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--로고와 사이트명 메뉴 바/로그인 아웃 -->\r\n");
      out.write("\t<div class=\"menuBar\">\r\n");
      out.write("\t\t<a href=\"index.jsp\"> <img src=\"./imgs/mainIcon4.jpg\"\r\n");
      out.write("\t\t\tstyle=\"width: 20%;\"></a>\r\n");
      out.write("\t\t<!-- 드랍메뉴들의 주 메뉴들 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t//\r\n");
      out.write("\t\t\t<div class=\"dropbtn\">\r\n");
      out.write("\t\t\t\tIntroduce\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t<a href=\"introduce.jsp\">회사 이력</a> <a href=\"location.jsp\">찾아 오시는 길</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t//\r\n");
      out.write("\t\t\t<div class=\"dropbtn\">\r\n");
      out.write("\t\t\t\tReservation\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t<a href=\"reservation_main.rsv\">예매 하기</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t//\r\n");
      out.write("\t\t\t<div class=\"dropbtn\">\r\n");
      out.write("\t\t\t\tSupport\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t<a href=\"AdminNotice.jsp\">공지 사항</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\" onclick=\"mypage(3)\">1:1 문의 하기</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"AllFAQ.jsp\">FAQ</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t//\r\n");
      out.write("\t\t\t<div class=\"dropbtn\">\r\n");
      out.write("\t\t\t\tMyPage\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\" onclick=\"mypage(1)\">정보 수정</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\" onclick=\"mypage(2)\">나의 예매/취소 내역</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"display: none;\" id=\"admin\">\r\n");
      out.write("\t\t\t//\r\n");
      out.write("\t\t\t\t<div class=\"dropbtn\">\r\n");
      out.write("\t\t\t\tAdmin\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t<a href=\"getAllSchedule.jsp\">스케쥴 관리</a> <a href=\"AdminNotice.jsp\">공지사항 작성</a> \r\n");
      out.write("\t\t\t\t\t<a href=\"#\">1:1문의 답변</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t//\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"index.jsp\"\r\n");
      out.write("\t\t\tstyle=\"text-decoration: none; position: absolute; right: 20px; color: white;\">\r\n");
      out.write("\t\t\t<span style=\"color: white;\">Kaja Airline</span><br>\r\n");
      out.write("\t\t</a> \r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" onclick=\"popupLogin()\" id=\"login\"\r\n");
      out.write("\t\t\tstyle=\"position: absolute; right: 20px; bottom: 10px; text-decoration: none; color: white;\">\r\n");
      out.write("\t\t로그인</a>\r\n");
      out.write("\t\t<span id=\"logout\" style=\"position: absolute; right: 20px; bottom: 10px;display: none;\">\r\n");
      out.write("\t\t<span style=\"font-style: italic;font-size: 12px;color: 586693;\">\r\n");
      out.write("\t\t\t");
      out.print(session.getAttribute("id") );
      out.write("님 환영합니다.:D<br>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t\t <a href=\"javascript:void(0)\" onclick=\"logout()\"\r\n");
      out.write("\t\t\tstyle=\"text-decoration: none; color: white; \">\r\n");
      out.write("\t\t로그아웃</a>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"./js/jquery-3.1.1.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tvar slideIndex = 0;\r\n");
      out.write("\tvar noticeIndex =0;\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\tfunction showSlides() {\r\n");
      out.write("\t\t/* css로 선언된 클래스 명에 대한 element를 가져와서 컨트롤 해줌.\r\n");
      out.write("\t\timg 슬라이드쇼 부분 헤더의 공지사항 슬라이드부분까지도 함꼐 구현*/\r\n");
      out.write("\t\tvar i;\r\n");
      out.write("\t\tvar slides = document.getElementsByClassName(\"imgSlides\");\r\n");
      out.write("\t\tvar dots = document.getElementsByClassName(\"dot\");\r\n");
      out.write("\t\tif(slides.length!=0){\r\n");
      out.write("\t\t\tfor (i = 0; i < slides.length; i++) {\r\n");
      out.write("\t\t\t\tslides[i].style.display = \"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tslideIndex++;\r\n");
      out.write("\t\t\tif (slideIndex > slides.length) {\r\n");
      out.write("\t\t\t\tslideIndex = 1\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(dots.length!=0){\r\n");
      out.write("\t\t\t\tfor (i = 0; i < dots.length; i++) {\r\n");
      out.write("\t\t\t\t\tdots[i].className = dots[i].className.replace(\" active\", \"\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tdots[slideIndex - 1].className += \" active\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tslides[slideIndex - 1].style.display = \"block\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/* notice */\r\n");
      out.write("\t\tvar notices = document.getElementsByClassName(\"noticeSlides\");\r\n");
      out.write("\t\tfor (i = 0; i < notices.length; i++) {\r\n");
      out.write("\t\t\tnotices[i].style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tnoticeIndex++;\r\n");
      out.write("\t\tif (noticeIndex > notices.length) {\r\n");
      out.write("\t\t\tnoticeIndex = 1\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tnotices[noticeIndex - 1].style.display = \"block\";\t\t\r\n");
      out.write("\t\tsetTimeout(showSlides, 3000); // 3초마다 다시 호출해서 계속 바뀌는 구성\r\n");
      out.write("\t\tcheckCookie();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction checkCookie(){\r\n");
      out.write("\t\t/* 쿠키가 있는지 확인후  section 높이조절 및 공지안보이게 */\r\n");
      out.write("\t\tvar sectionId=document.getElementById(\"sectionId\");\r\n");
      out.write("\t\tvar dis=document.getElementsByClassName(\"notice-container\");\r\n");
      out.write("\t\t/* var hMenu=document.getElementsByClassName(\"menu\"); */\r\n");
      out.write("\t\tif(document.cookie==\"kajaAirline=done\"){\r\n");
      out.write("\t\t\tvar sectionId=document.getElementById(\"sectionId\");\r\n");
      out.write("\t\t\tsectionId.style.marginTop=\"11%\";\r\n");
      out.write("\t\t\tdis[0].style.display=\"none\";\r\n");
      out.write("\t\t\t/* hMenu[0].style.top=\"19.1%\"; */\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tsectionId.style.marginTop=\"13%\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*onload가 하나만 돌아가므로 여기서 로그인 로그아웃 보이는 부분까지 처리  */\r\n");
      out.write("\t\tif(\"");
      out.print((String)session.getAttribute("id"));
      out.write("\"!=\"null\"){\r\n");
      out.write("\t\t\t/* 로그인이 되있는 상태면 */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar login=document.getElementById(\"login\");\r\n");
      out.write("\t\t\tvar logout=document.getElementById(\"logout\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlogin.style.display=\"none\";\r\n");
      out.write("\t\t\tlogout.style.display=\"block\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(\"");
      out.print((String)session.getAttribute("id"));
      out.write("\"==\"admin\"){\r\n");
      out.write("\t\t\t\tvar adminMenu=document.getElementById(\"admin\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(adminMenu.style.display==\"none\")\r\n");
      out.write("\t\t\t\t\tadminMenu.style.display=\"inline-block\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/* 이 헤더 onload후 돌아갈 include 해준 jsp의 onload function call */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tfunction setCookie() {\r\n");
      out.write("\t\t/*공지사항 부분 x표시를 누를때 콜되는 함수 체크 박스체크 여부까지 확인후 쿠키셋팅  */\r\n");
      out.write("\t\tvar chk=document.getElementsByName(\"cook\");\r\n");
      out.write("\t\tvar hMenu=document.getElementsByClassName(\"menu\");\r\n");
      out.write("\t\tif(chk[0].checked){\r\n");
      out.write("\t\t\tvar todayDate = new Date();\r\n");
      out.write("\t\t    todayDate.setDate(todayDate.getDate() + 1);\r\n");
      out.write("\t\t    document.cookie = \"kajaAirline=done; path=/; expires=\" + todayDate.toGMTString() + \";\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    var dis=document.getElementsByClassName(\"notice-container\");\r\n");
      out.write("\t    var sectionId=document.getElementById(\"sectionId\");\r\n");
      out.write("\t    dis[0].style.display=\"none\";\r\n");
      out.write("\t    sectionId.style.marginTop=\"11%\";\r\n");
      out.write("\t    hMenu[0].style.top=\"19.1%\";\r\n");
      out.write("\t    \r\n");
      out.write("\t}\r\n");
      out.write("\t/* 로그인 체크 함수/회원가입 가는 함수*/\r\n");
      out.write("\t\r\n");
      out.write("\tfunction popupLogin2(){\r\n");
      out.write("\t\t//하나로 통합되었다가..오류로 인해서 나눠짐. 로그인 박스 안의 x 표 클릭시 실행\r\n");
      out.write("\t\tvar popup = document.getElementsByClassName(\"login\");\r\n");
      out.write("\t\tvar header = document.getElementsByTagName(\"header\");\r\n");
      out.write("\t\tvar nav = document.getElementsByTagName(\"nav\");\r\n");
      out.write("\t\tvar section = document.getElementsByTagName(\"section\");\r\n");
      out.write("\t\tvar footer = document.getElementsByTagName(\"footer\");\r\n");
      out.write("\t\tpopup[0].style.display = \"none\";\r\n");
      out.write("\t\tnav[0].style.opacity = \"1\"; \r\n");
      out.write("\t\tsection[0].style.opacity = \"1\";\r\n");
      out.write("\t\tfooter[0].style.opacity = \"1\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction popupLogin(){\r\n");
      out.write("\t/* 로그인 버튼시 팝업모양으로 로그인창이 보여짐. */\r\n");
      out.write("\t/* 로그인 후의 다시 열릴때도 불려지므로 조건문으로 경우들 처리*/\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t//로그인이 안되어서 id가 없다 페이지 열릴때마다 체크하니....\r\n");
      out.write("\t\t\tvar popup = document.getElementsByClassName(\"login\");\r\n");
      out.write("\t\t\tvar header = document.getElementsByTagName(\"header\");\r\n");
      out.write("\t\t\tvar nav = document.getElementsByTagName(\"nav\");\r\n");
      out.write("\t\t\tvar section = document.getElementsByTagName(\"section\");\r\n");
      out.write("\t\t\tvar footer = document.getElementsByTagName(\"footer\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (popup[0].style.display == \"none\" || \"");
      out.print((String)session.getAttribute("result"));
      out.write("\"==\"id\"\r\n");
      out.write("\t\t\t\t\t|| \"");
      out.print((String)session.getAttribute("result"));
      out.write("\"==\"pw\" || popup[0].style.display == \"\") {\r\n");
      out.write("\t\t\t\tpopup[0].style.display = \"block\";\r\n");
      out.write("\t\t\t\t/* nav[0].style.opacity = \"0.3\"; */\r\n");
      out.write("\t\t\t\tsection[0].style.opacity = \"0.3\";\r\n");
      out.write("\t\t\t\tfooter[0].style.opacity = \"0.3\";\r\n");
      out.write("\t\t\t\tpopup[0].style.opacity = \"1\";\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\tpopup[0].style.display = \"none\";\r\n");
      out.write("\t\t\t\t/* nav[0].style.opacity = \"1\";  */\r\n");
      out.write("\t\t\t\tsection[0].style.opacity = \"1\";\r\n");
      out.write("\t\t\t\tfooter[0].style.opacity = \"1\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction login() {\r\n");
      out.write("\t\t/* 회원체크 */\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttypes: \"post\",\r\n");
      out.write("\t\t\turl : \"checkLogin.indexdo\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tid : $(\"#clientId\").val(),\r\n");
      out.write("\t\t\t\tpw : $(\"#clientPw\").val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\tsuccess : function(re) {\r\n");
      out.write("\t\t\t\talert(re);\r\n");
      out.write("\t\t\t\tif(location.href==\"http://localhost:8081/KajaAirline/Signup.jsp\")\r\n");
      out.write("\t\t\t\t\tlocation.href=\"index.jsp\";\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\tlocation.reload();\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(re){\r\n");
      out.write("\t\t\t\talert(\"에러발생!\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction logout(){\r\n");
      out.write("\t\t/* 세션을 여기서 자바코드로 지우면 실행 순서로 인해서 바로 삭제되서 로그아웃 함수를 만듬 */\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttypes: \"post\",\r\n");
      out.write("\t\t\turl : \"checkLogin.indexdo\",\r\n");
      out.write("\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\tsuccess : function(re) {\r\n");
      out.write("\t\t\t\tlocation.replace(\"index.jsp\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(re){\r\n");
      out.write("\t\t\t\talert(\"에러발생!\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changePw(x){\r\n");
      out.write("\t\tdocument.getElementById(x).type=\"password\";\r\n");
      out.write("\t\tdocument.getElementById(x).value=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction mypage(num){\r\n");
      out.write("\t\tif(\"");
      out.print(session.getAttribute("id"));
      out.write("\"!=\"null\"){\r\n");
      out.write("\t\t\tif(num==1)\r\n");
      out.write("\t\t\t\tlocation.href=\"selectClients.mypage\";\r\n");
      out.write("\t\t\telse if(num==2)\r\n");
      out.write("\t\t\t\tlocation.href=\"reservation.mypage\";\r\n");
      out.write("\t\t\telse if(num==3)\r\n");
      out.write("\t\t\t\tlocation.href=\"write_Inquire.jsp\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"로그인을 먼저 해주세요~!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
