/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-07-17 10:00:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Kaja~가자 Airline</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* The dots/bullets/indicators */\r\n");
      out.write(".dot {\r\n");
      out.write("  height: 15px;\r\n");
      out.write("  width: 15px;\r\n");
      out.write("  margin: 0 2px;\r\n");
      out.write("  background-color: #bbb;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  transition: background-color 0.6s ease;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".active {\r\n");
      out.write("  background-color: #717171;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* menu set */\r\n");
      out.write(".menu{\r\n");
      out.write("\twidth: 22%;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 22.1%;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\tbackground-color:white;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tz-index: 80;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menuB{\r\n");
      out.write("\tfont-size: 20pt;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: fixed; \r\n");
      out.write("\ttop : 23%;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\twidth: 5%;\r\n");
      out.write("\tz-index: 95;\r\n");
      out.write("}\r\n");
      out.write(".menuDot{\r\n");
      out.write("\tright : 5px;\r\n");
      out.write("\tposition :absolute;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write(" \twidth: 20px;\r\n");
      out.write("\tborder-radius: 50%; \r\n");
      out.write("\tbackground-color:#c4c3bb;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin : 6px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tz-index: 98;\r\n");
      out.write("}\r\n");
      out.write(".menuText{\r\n");
      out.write("\tfont-size: 13pt;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".way{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
request.setCharacterEncoding("EUC-KR"); 
	response.setCharacterEncoding("EUC-KR");
      out.write("\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<a href=\"#\"><img class=\"menuB\" src=\"./imgs/menu.jpg\" onclick=\"showMenu()\"><br></a>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- <nav>\r\n");
      out.write("\t\t숨겨지는 탭메뉴 간단 예매부분 \r\n");
      out.write("\t</nav> -->\r\n");
      out.write("\t<nav class=\"menu\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"reservation_result.rsv\" method=\"post\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"menuText\">\r\n");
      out.write("\t\t\t\t<h2>Kaja Airline 간편 조회<a href=\"#\">\r\n");
      out.write("\t\t\t\t<span class=\"menuDot\" onclick=\"showMenu()\">X</span>\r\n");
      out.write("\t\t\t\t</a></h2>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" value=\"편도\" name=\"tripType\" checked=\"checked\" onchange=\"findWay()\">편도&nbsp; \r\n");
      out.write("\t\t\t\t<input type=\"radio\" value=\"왕복\" name=\"tripType\" onchange=\"findWay()\">왕복 \r\n");
      out.write("\t\t\t\t<br><hr>\r\n");
      out.write("\t\t\t\t출발지<br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" onfocus=\"this.select()\" name=\"depAirport\">\r\n");
      out.write("\t\t\t\t<br><br> \r\n");
      out.write("\t\t\t\t도착지<br><input type=\"text\" onfocus=\"this.select()\" name=\"arrAirport\">\r\n");
      out.write("\t\t\t\t<br><br> \r\n");
      out.write("\t\t\t\t가는날<br>\r\n");
      out.write("\t\t\t\t<input type=\"date\" name=\"goDate\"><br><br> \r\n");
      out.write("\t\t\t\t<div class=\"way\">\r\n");
      out.write("\t\t\t\t\t오는날 <br>\r\n");
      out.write("\t\t\t\t\t<input type=\"date\" name=\"comeDate\"><br> <br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"adultCount\" value=\"1\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"childCount\" value=\"0\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"babyCount\" value=\"0\"> \r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"예매하기\" style=\"height: 40px; width: 150px; font-weight: bold;\">\r\n");
      out.write("\t\t\t\t<br></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <section> indexPage 이미지슬라이드 -->\r\n");
      out.write("\t<section id=\"sectionId\">\r\n");
      out.write("\t\t<div class=\"slideshow-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"imgSlides fade\" style=\"display: block;\">\r\n");
      out.write("\t\t\t\t<img src=\"./imgs/index1.jpg\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t<div class=\"text\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"imgSlides fade\">\r\n");
      out.write("\t\t\t\t<img src=./imgs/index2.jpg style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t<div class=\"text\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"imgSlides fade\">\r\n");
      out.write("\t\t\t\t<img src=\"./imgs/index3.jpg\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t<div class=\"text\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"imgSlides fade\">\r\n");
      out.write("\t\t\t\t<img src=\"./imgs/index4.jpg\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t<div class=\"text\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t<span class=\"dot\"></span> <span class=\"dot\"></span> \r\n");
      out.write("\t\t\t\t<span class=\"dot\"></span> <span class=\"dot\"></span>\r\n");
      out.write("\t\t\t\t<!--dot들에 클릭시 바뀌는 것까지 추가해야함  -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- </section> -->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("<script src=\"./js/jquery-3.1.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("showSlides();\r\n");
      out.write("function showMenu(){\r\n");
      out.write("\t/* 숨겨지는 탭 구현을 위한 함수 */\r\n");
      out.write("\tvar menu=document.getElementsByClassName(\"menu\");\r\n");
      out.write("\tvar menuB=document.getElementsByClassName(\"menuB\");\r\n");
      out.write("\tvar container=document.getElementsByClassName(\"slideshow-container\");\r\n");
      out.write("\tif(menu[0].style.display==\"block\"){\r\n");
      out.write("\t\tmenu[0].style.display=\"none\";\r\n");
      out.write("\t\tmenuB[0].style.display=\"block\";\r\n");
      out.write("\t\tcontainer[0].style.width=\"100%\";\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tmenu[0].style.display=\"block\";\r\n");
      out.write("\t\tmenuB[0].style.display=\"none\";\r\n");
      out.write("\t\tcontainer[0].style.width=\"77%\";\r\n");
      out.write("\t} \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function findWay(){\r\n");
      out.write("\t/* 간편 예매조회 부분 편도 왕복에 따른 2번째 출발지 display 조정 */\r\n");
      out.write("\tvar way=document.getElementsByName(\"tripType\");\r\n");
      out.write("\tvar twoWay=document.getElementsByClassName(\"way\");\r\n");
      out.write("\tif(twoWay[0].style.display==\"block\")\r\n");
      out.write("\t\ttwoWay[0].style.display=\"none\";\r\n");
      out.write("\telse\r\n");
      out.write("\t\ttwoWay[0].style.display=\"block\";\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
