/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-07-17 09:04:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class introduce_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("\tbackground-image: url(\"./imgs/bg.jpg\");\r\n");
      out.write("}\r\n");
      out.write("\t.introduceTable{\r\n");
      out.write("\t\tmargin-left: auto;\r\n");
      out.write("\t\tmargin-right: auto;\r\n");
      out.write("\t\twidth: 80%;\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t}\t\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"./js/jquery-3.1.1.js\"charset=\"euc-kr\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.onload=function setSign() {\r\n");
      out.write("\tshowSlides();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<section id=\"sectionId\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<table class=\"introduceTable\">\r\n");
      out.write("\t\t\t<tr><td colspan=\"2\" style=\"text-align: center;font-size: 25pt;\">\r\n");
      out.write("\t\t\t\tKaja Airline\r\n");
      out.write("\t\t\t</td></tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"width: 50%;\">\r\n");
      out.write("\t\t\t\t<p style=\"font-size: 20pt;\">회사 소개</p>\r\n");
      out.write("\t\t\t\t<p style=\"font-size: 13pt;line-height: 130%;\">&nbsp;2020년 '최고의 안전과 서비스, 저렴한 가격을 통한<br> \r\n");
      out.write("\t\t\t\t고객 만족'이라는 경영이념으로 창립된 Kaja Airline은 <br>\r\n");
      out.write("\t\t\t\t미래 전 세계에 색동날개를 펼치는 글로벌 항공사로 성장하여<br>\r\n");
      out.write("\t\t\t\t색동 날개 만큼이나 친절하고 참신하며 정성 어린 서비스로<br>\r\n");
      out.write("\t\t\t\t고객에게 다가가고자 합니다.<br>\r\n");
      out.write("\t\t\t\t저희 Kaja Airline은 최신 설비로 안전을 최우선으로<br>\r\n");
      out.write("\t\t\t\t추구하며 미래를 향한 비상을 계속하고 있습니다.<br>\r\n");
      out.write("\t\t\t\t언젠가는 업계 최고 1등의 기업가치를 창출하는 아름다운 <br>\r\n");
      out.write("\t\t\t\t기업으로서의 역할을 다하고자 끊임없는 노력을 기울이고 있습니다.<br>\r\n");
      out.write(" \t\t\t\t또한 윤리/환경/상생 경영 및 사회공헌에 이르기까지 <br>\r\n");
      out.write(" \t\t\t\t기업의 사회적 책임을 다하여 지속 가능한 성장을 추구하는 <br>\r\n");
      out.write(" \t\t\t\t세계 최고의 항공사가 되고자 합니다.<br>\r\n");
      out.write("\t\t\t\t저희 Kaja Airline과 함께 즐겁고 편안한 여행 되시길 바랍니다.</p>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"slideshow-container\" style=\"width: 50%;\">\r\n");
      out.write("\t\t\t\t<div class=\"imgSlides fade\" style=\"display: block;\"><br>\r\n");
      out.write("\t\t\t\t\t<img src=\"./imgs/testAirPort1.jpg\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"imgSlides fade\"><br>\r\n");
      out.write("\t\t\t\t\t<img src=./imgs/testAirPort2.jpg style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
